language: go

go:
    - "1.13"
    - "1.14"
    - master

script:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    - go test ./...
    - go test -v -covermode=count -coverprofile=coverage.out
    - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
